use crate::keymap::KeyPosition;

// Logical key → HID keycode
pub fn keycode(pos: KeyPosition) -> u8 {
    match pos {
        KeyPosition::Escape       => 0x29,
 //       KeyPosition::Backtick     => 0x35,
        KeyPosition::N1           => 0x1E,
        KeyPosition::N2           => 0x1F,
        KeyPosition::N3           => 0x20,
        KeyPosition::N4           => 0x21,
        KeyPosition::N5           => 0x22,
        KeyPosition::N6           => 0x23,
        KeyPosition::N7           => 0x24,
        KeyPosition::N8           => 0x25,
        KeyPosition::N9           => 0x26,
        KeyPosition::N0           => 0x27,
        KeyPosition::Minus        => 0x2D,
        KeyPosition::Equals       => 0x2E,
        KeyPosition::Backspace    => 0x2A,
        KeyPosition::Tab          => 0x2B,
        KeyPosition::Q            => 0x14,
        KeyPosition::W            => 0x1A,
        KeyPosition::E            => 0x08,
        KeyPosition::R            => 0x15,
        KeyPosition::T            => 0x17,
        KeyPosition::Y            => 0x1C,
        KeyPosition::U            => 0x18,
        KeyPosition::I            => 0x0C,
        KeyPosition::O            => 0x12,
        KeyPosition::P            => 0x13,
        KeyPosition::LeftBracket  => 0x2F,
        KeyPosition::RightBracket => 0x30,
        KeyPosition::Backslash    => 0x31,
        KeyPosition::CapsLock     => 0x39,
        KeyPosition::A            => 0x04,
        KeyPosition::S            => 0x16,
        KeyPosition::D            => 0x07,
        KeyPosition::F            => 0x09,
        KeyPosition::G            => 0x0A,
        KeyPosition::H            => 0x0B,
        KeyPosition::J            => 0x0D,
        KeyPosition::K            => 0x0E,
        KeyPosition::L            => 0x0F,
        KeyPosition::Semicolon    => 0x33,
        KeyPosition::Quote        => 0x34,
        KeyPosition::Enter        => 0x28,
        KeyPosition::LeftShift    => 0xE1,
        KeyPosition::RightShift   => 0xE5,
        KeyPosition::Z            => 0x1B,
        KeyPosition::X            => 0x1D,
        KeyPosition::C            => 0x06,
        KeyPosition::V            => 0x19,
        KeyPosition::B            => 0x05,
        KeyPosition::N            => 0x11,
        KeyPosition::M            => 0x10,
        KeyPosition::Comma        => 0x36,
        KeyPosition::Dot          => 0x37,
        KeyPosition::Slash        => 0x38,
        KeyPosition::LeftCtrl     => 0xE0,
        KeyPosition::LeftAlt      => 0xE2,
        KeyPosition::LeftGui      => 0xE3,
        KeyPosition::Space        => 0x2C,
        KeyPosition::RightAlt     => 0xE6,
        KeyPosition::Fn           => 0x00, // No standard HID code for Fn
        KeyPosition::LeftArrow    => 0x50,
        KeyPosition::DownArrow    => 0x51,
        KeyPosition::UpArrow      => 0x52,
        KeyPosition::RightArrow   => 0x4F,
        KeyPosition::Backtick     => 0x35,
        KeyPosition::PageUp        => 0x4B,
        KeyPosition::PageDown      => 0x4E,
        KeyPosition::Delete        => 0x4C,
    }
}
